-- MySQL Script generated by MySQL Workbench
-- 10/10/23 15:44:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sentimental-connect
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sentimental-connect` ;

-- -----------------------------------------------------
-- Schema sentimental-connect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sentimental-connect` DEFAULT CHARACTER SET utf8 ;
USE `sentimental-connect` ;

-- -----------------------------------------------------
-- Table `sentimental-connect`.`Schools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentimental-connect`.`Schools` ;

CREATE TABLE IF NOT EXISTS `sentimental-connect`.`Schools` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` ENUM('Primary', 'Secondary', 'Higher Education') NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `year_founded` INT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '		';


-- -----------------------------------------------------
-- Table `sentimental-connect`.`school_affiliation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentimental-connect`.`school_affiliation` ;

CREATE TABLE IF NOT EXISTS `sentimental-connect`.`school_affiliation` (
  `school_id` INT NOT NULL,
  `school_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `degreee_type` VARCHAR(10) NULL,
  `Schools_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`school_id`, `school_id`, `Schools_id`),
  CONSTRAINT `fk_school_affiliation_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `sentimental-connect`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_school_affiliation_Schools1_idx` ON `sentimental-connect`.`school_affiliation` (`Schools_id` ASC);


-- -----------------------------------------------------
-- Table `sentimental-connect`.`company_affiliation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentimental-connect`.`company_affiliation` ;

CREATE TABLE IF NOT EXISTS `sentimental-connect`.`company_affiliation` (
  `user_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`user_id`, `company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sentimental-connect`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentimental-connect`.`Users` ;

CREATE TABLE IF NOT EXISTS `sentimental-connect`.`Users` (
  `id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `Users_id` INT UNSIGNED NOT NULL,
  `school_affiliation_school_id` INT NOT NULL,
  `school_affiliation_school_id1` INT NOT NULL,
  `company_affiliation_user_id` INT NOT NULL,
  `company_affiliation_company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Users_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `sentimental-connect`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_school_affiliation1`
    FOREIGN KEY (`school_affiliation_school_id` , `school_affiliation_school_id1`)
    REFERENCES `sentimental-connect`.`school_affiliation` (`school_id` , `school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_company_affiliation1`
    FOREIGN KEY (`company_affiliation_user_id` , `company_affiliation_company_id`)
    REFERENCES `sentimental-connect`.`company_affiliation` (`user_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '	';

CREATE INDEX `fk_Users_Users_idx` ON `sentimental-connect`.`Users` (`Users_id` ASC);

CREATE INDEX `fk_Users_school_affiliation1_idx` ON `sentimental-connect`.`Users` (`school_affiliation_school_id` ASC, `school_affiliation_school_id1` ASC);

CREATE INDEX `fk_Users_company_affiliation1_idx` ON `sentimental-connect`.`Users` (`company_affiliation_user_id` ASC, `company_affiliation_company_id` ASC);


-- -----------------------------------------------------
-- Table `sentimental-connect`.`Companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentimental-connect`.`Companies` ;

CREATE TABLE IF NOT EXISTS `sentimental-connect`.`Companies` (
  `id` INT UNSIGNED NOT NULL,
  `industry` ENUM('Technology', 'Education', 'Business') NULL,
  `location` VARCHAR(45) NULL,
  `company_affiliation_user_id` INT NOT NULL,
  `company_affiliation_company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `company_affiliation_user_id`, `company_affiliation_company_id`),
  CONSTRAINT `fk_Companies_company_affiliation1`
    FOREIGN KEY (`company_affiliation_user_id` , `company_affiliation_company_id`)
    REFERENCES `sentimental-connect`.`company_affiliation` (`user_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Companies_company_affiliation1_idx` ON `sentimental-connect`.`Companies` (`company_affiliation_user_id` ASC, `company_affiliation_company_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
